<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BatchProcess3</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="Controls\FilterButton.axaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Controls\FilterButton.axaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Black.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Bold.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-ExtraBold.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Extralight.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Light.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Medium.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Regular.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Semibold.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP-Thin.ttf" />
    <AvaloniaResource Include="Assets\Fonts\NotoSansJP.ttf" />
    <AvaloniaResource Include="Assets\Fonts\Phosphor-Fill.ttf" />
    <AvaloniaResource Include="Assets\Fonts\Phosphor.ttf" />
    <AvaloniaResource Include="Assets\Images\background-settings.svg" />
    <AvaloniaResource Include="Assets\Images\icon.svg" />
    <AvaloniaResource Include="Assets\Images\logo.svg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.13" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="12.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Pages\MainView.axaml.cs">
      <DependentUpon>MainView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\" />
  </ItemGroup>
</Project>
